# Generated by Django 5.1.7 on 2025-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_verfiedusers_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='custplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('planlist', models.TextField()),
            ],
        ),
    ]
