# Generated by Django 5.1.7 on 2025-04-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_custplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='plancust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100)),
                ('items', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='custplan',
            name='planlist',
            field=models.JSONField(),
        ),
    ]
