# Generated by Django 5.1.7 on 2025-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_plancust_alter_custplan_planlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_images', models.JSONField()),
            ],
        ),
    ]
