# Generated by Django 5.1.7 on 2025-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_sendimg_imgpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendimg',
            name='imgpath',
            field=models.TextField(),
        ),
    ]
