# Generated by Django 5.1.7 on 2025-04-13 17:18

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_sendimg_imgpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='customplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=20)),
                ('chest', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('triceps', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('shoulder', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('back', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('biceps', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('legs', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
            ],
        ),
    ]
