# Generated by Django 5.1.7 on 2025-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_register_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='verified_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('password', models.EmailField(max_length=255)),
                ('gender', models.EmailField(max_length=255)),
                ('dob', models.EmailField(max_length=255)),
            ],
        ),
    ]
