# Generated by Django 5.1.7 on 2025-06-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_verified_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customplan',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
