# Generated by Django 5.1.7 on 2025-06-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_customplan_contact_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sendimg',
        ),
        migrations.DeleteModel(
            name='verfiedusers',
        ),
    ]
